// diff_in.v

// Generated using ACDS version 18.0 219

`timescale 1 ps / 1 ps
module diff_in (
		output wire [0:0] dout,     //     dout.export
		input  wire [0:0] pad_in,   //   pad_in.export
		input  wire [0:0] pad_in_b  // pad_in_b.export
	);

	diff_in_altera_gpio_180_bency7y gpio_0 (
		.dout     (dout),     //  output,  width = 1,     dout.export
		.pad_in   (pad_in),   //   input,  width = 1,   pad_in.export
		.pad_in_b (pad_in_b)  //   input,  width = 1, pad_in_b.export
	);

endmodule
